# This logging yaml file came to us through Piero Madarp,
# who says he got it from a friend.

---
    version: 1
    disable_existing_loggers: False
    formatters:
        simple:
            format: '%(asctime)s.%(msecs)03d %(name)-12s %(levelname)-8s [%(threadName)-12s] %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
            # format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            level: INFO
            formatter: simple
            stream: ext://sys.stdout
        file_handler:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: debug.log
            maxBytes: 10485760 # 10MB
            backupCount: 5
            encoding: utf8        
        info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: info.log
            maxBytes: 10485760 # 10MB
            backupCount: 5
            encoding: utf8
        # error_file_handler:
        #     class: logging.handlers.RotatingFileHandler
        #     level: ERROR
        #     formatter: simple
        #     filename: errors.log
        #     maxBytes: 10485760 # 10MB
        #     backupCount: 5
        #     encoding: utf8
    loggers:
        '':
            level: DEBUG
            handlers: [console, file_handler]
            propagate: no
    root:
        level: NOTSET
        #handlers: [console, info_file_handler, error_file_handler]
        handlers: [console, info_file_handler]
    